### ISSUE TITLE
Not compatible with laravel11

### ISSUE THREAD

**Issue by robin-dongbin** [hybridly/hybridly#125]
### Describe the bug

Http/Kernel.php does not exist in the newly created laravel11 project and cannot be installed

### Reproduction

no need

### System information

```bash
no need
```

### Used package manager

npm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
I don't understand what you mean. I'm already running Hybridly in production right now on Laravel 11. Can you be more specific or provide a reproduction please?

**Comment by robin-dongbin** [comment]
@innocenzi I'm talking about create a new larval 11 project and install this package. You will know the error. Not update to larval 11, create a new one.

**Comment by innocenzi** [comment]
I tried creating a new project:

```bash
composer create-project laravel/laravel laravel
cd laravel
npx @preset/cli apply hybridly/preset
```

Everything works. I'm assuming you encountered this issue? https://github.com/hybridly/hybridly/issues/126

**Comment by robin-dongbin** [comment]
No, I run this, it not works
```
composer require hybridly/laravel
php artisan hybridly:install
```

**Comment by robin-dongbin** [comment]
@innocenzi I updated to latest version. the issue is still exist.

**Comment by RobertBoes** [comment]
@robin-dongbin For maintainers it's helpful to share as much information as possible, that way it's easy to know what's going on and at what step it's failing. So sharing logs / errors is really helpful, much more helpful than "it's not working"

So I've tried this and it fails on the step where the install command is trying to modify the Http Kernel, since that doesn't exist anymore in Laravel 11.
```sh
php artisan hybridly:install

   INFO  Hybridly middleware [app/Http/Middleware/HandleHybridRequests.php] created successfully.


   ErrorException

  file_get_contents([... path to app ...]/app/Http/Kernel.php): Failed to open stream: No such file or directory

  at vendor/hybridly/laravel/src/Commands/InstallCommand.php:35
     31▕     }
     32▕
     33▕     protected function installMiddlewareAfter($after, $name, $group = 'web')
     34▕     {
  ➜  35▕         $httpKernel = file_get_contents(app_path('Http/Kernel.php'));
     36▕
     37▕         $middlewareGroups = str($httpKernel)->betweenFirst('$middlewareGroups = [', '];');
     38▕         $middlewareGroup = str($middlewareGroups)->betweenFirst("'{$group}' => [", '],');
     39▕

      +15 vendor frames

  16  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
```

**Comment by robin-dongbin** [comment]
@RobertBoes Sorry, I thought my bug description said what the problem was.
So I did not post the error information
Next time I will post the error information.

**Comment by innocenzi** [comment]
Thanks @RobertBoes! This will be fixed in the next version, which I plan to release next week (need an upstream bugfix before).
