### ISSUE TITLE
Use of unknown class: 'Tests\CreatesApplication'

### ISSUE THREAD

**Issue by fabiorodriguesroque** [hybridly/hybridly#131]
### Describe the bug

Hey @innocenzi 

After install hybridly with the preset, some stuff are added to TestCase including the CreatesApplication trait that doesn't exists on laravel 11. 

### Reproduction

https://github.com/fabiorodriguesroque/laravel-hybridly

### Steps to reproduce

1. Install fresh app
2. run tests
3. Install hybridly
4. run tests -> will fail because trait doesn't exists.

### System information

```bash
System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 201.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.7.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 16.3
  npmPackages:
    hybridly: ^0.7.2 => 0.7.2
```

### Used package manager

npm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
Thanks! It was due to scaffolding changes.
