### ISSUE TITLE
Preloaded URLs also affect non-GET urls if the path is the same

### ISSUE THREAD

**Issue by jaggy** [hybridly/hybridly#143]
### Describe the bug

When a URL is preloaded, form submissions end up redirecting if the URLs have the same route despite having different HTTP methods.

Example:
- `GET /users/1`
- `PUT /users/1`

If `/users/1` is preloaded, then submitting a form via `useForm()` or `router.put` will instead perform `GET /users/1`.

### Reproduction

https://github.com/jaggy/hybridly-preloading-bug-reproduction

### Steps to reproduce

In the reproduction repo:
- Clicking the form submit will submit the form.
- Preloading the link, /then/ submitting the form will perform a redirect

Here's a video showing the error.

https://github.com/hybridly/hybridly/assets/1993075/25cbe253-e9d0-4fc8-adcb-0da94638646e

### System information

```bash
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 119.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 3.3.1 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/Library/Application Support/Herd/config/nvm/versions/node/v20.11.1/bin/npm
    pnpm: 7.19.0 - ~/Library/pnpm/pnpm
    bun: 1.0.33 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.122
    Safari: 17.4.1
    Safari Technology Preview: 17.4
  npmPackages:
    hybridly: ^0.7.3 => 0.7.3
```

### Used package manager

npm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
Thank you for the report!
