### ISSUE TITLE
`useForm` inconsistent behavior with `PUT` and `DELETE`

### ISSUE THREAD

**Issue by jaggy** [hybridly/hybridly#145]
### Describe the bug

It seems that the useForm behavior is inconsistent based on if `fields: {}` is added or not.

```
// uses POST
useForm({ method: 'PUT', fields: {} }) 
useForm({ method: 'DELETE', fields: {} }) 

// uses PUT/DELETE
useForm({ method: 'PUT' })
useForm({ method: 'DELETE' }) 
```

I'm not really sure what the expected behavior is. This could be intended as is, but I thought the `fields: {}` attribute required since typescript throws a fit when I don't add it despite using DELETE for the form.

### Reproduction

https://github.com/jaggy/hybridly-form-delete-bug

### Steps to reproduce

I've made endpoints so it's easier to test.
- PUT WITH fields
- PUT WITHOUT fields
- DELETE WITH fields
- DELETE WITHOUT fields

https://github.com/hybridly/hybridly/assets/1993075/4cc3e510-830e-4c28-9965-1dc1cf059f77

### System information

```bash
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 47.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 3.3.1 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/Library/Application Support/Herd/config/nvm/versions/node/v20.11.1/bin/npm
    pnpm: 7.19.0 - ~/Library/pnpm/pnpm
    bun: 1.0.33 - ~/.bun/bin/bun
  Browsers:
    Chrome: 124.0.6367.60
    Safari: 17.4.1
    Safari Technology Preview: 17.4
  npmPackages:
    hybridly: ^0.7.3 => 0.7.3
```

### Used package manager

npm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
Thank you! Good catch, and amazing reproduction 👌
