### ISSUE TITLE
[Laravel Octane] Shared data between middleware seem to leak with one another

### ISSUE THREAD

**Issue by jaggy** [hybridly/hybridly#148]
### Describe the bug

When having multiple HandleHybridRequests, it seems that the variables between the two middleware leak into each other.

An example when to need multiple Hybridly middleware is when having multiple route groups. ie: Marketing/Admin/Control Panel/App/Staff which will have different global properties.

### Reproduction

https://github.com/jaggy/hybridly-octane-issue

### Steps to reproduce

- Start Octane with Swoole
  - Seems to work with Roadrunner.
- Visit /one
  - This will show the correct global properties filled. Only `one` and `lazyOne` will be filled.
- Visit /two
  - This will have `two` and `lazyTwo filled, but ALSO `one` and `lazyOne` which are only in the previous middleware group.

Here's a video of the issue

https://github.com/hybridly/hybridly/assets/1993075/3e6302dd-9269-425a-bd51-311672a42865

### System information

```bash
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 256.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Yarn: 3.3.1 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/Library/Application Support/Herd/config/nvm/versions/node/v20.11.1/bin/npm
    pnpm: 7.19.0 - ~/Library/pnpm/pnpm
    bun: 1.0.33 - ~/.bun/bin/bun
  Browsers:
    Chrome: 124.0.6367.91
    Safari: 17.4.1
    Safari Technology Preview: 17.4
  npmPackages:
    hybridly: ^0.7.7 => 0.7.7
```

### Used package manager

npm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
Can you try https://github.com/hybridly/hybridly/pull/150 and let me know if that works for you?

**Comment by jaggy** [comment]
@innocenzi did a quick test and it looks good with Swoole!
