### ISSUE TITLE
Demonstration video not working

### ISSUE THREAD

**Issue by Wulfheart** [hybridly/hybridly#17]
### Describe the bug

See above. I am using an iPad. 

### Reproduction

https://hybridly.dev/guide/demonstration.html

### System information

```bash
iOS 16.1.1
```

### Used package manager

npm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/hybridly/hybridly/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
Thanks, indeed Safari on iOS is the only browser not supporting webm. I'll see if I can add a fallback

**Comment by innocenzi** [comment]
I think I won't add a fallback video so it doesn't add a few MB on the repository just for iOS Safari support. Thanks for the report and here's the video in another format:

https://user-images.githubusercontent.com/16060559/201891747-1d8110ee-ea20-4ab8-a354-0c6642c5e102.mp4

**Comment by HassanZahirnia** [comment]
Would it be possible to use a video cdn for this matter? (or any video content platform)
So hopefully it enables cross platform video watching + reduce repo size + enable to provide more video examples in the future

**Comment by innocenzi** [comment]
Would be nice but had no idea which one to use. Wanted to use Vimeo but didn't manage to integrate them cleanly. Totally open to suggestions
