### ISSUE TITLE
Laravel 11.9 preset issue

### ISSUE THREAD

**Issue by cgslivre** [hybridly/hybridly#191]
### Describe the bug

Congratulations on your work @innocenzi !

I tried to test it by following the tutorial described at:
https://hybridly.dev/guide/installation.html#preset

I get the following package compatibility error:
```bash
bunx @preset/cli apply hybridly/preset
```
```bash
  ERROR  Failed applying laravel:hybridly.

  ✓  Executed action: install Pest (preset: laravel:pest)
    ✓  Executed action: register the composer plugin
    ✓  Executed action: remove phpunit
    ✓  Executed action: install dependencies (php)
    ✓  Executed action: setup Pest
  ✓  Executed action: delete unused project files
  ✓  Executed action: update .gitignore
  ✓  Executed action: add middleware
  ✓  Executed action: extract templates
  ✓  Executed action: remove unused dependencies
  ✓  Executed action: add npm dependencies (node)
  ✓  Executed action: configure PostCSS
  ×  Failed action: add php dependencies (php)
     ↪  Command failed with exit code 2: composer require --no-interaction hybridly/laravel spatie/laravel-data
      ./composer.json has been updated
      Running composer update hybridly/laravel spatie/laravel-data
      Loading composer repositories with package information
      Updating dependencies
      Your requirements could not be resolved to an installable set of packages.

        Problem 1
          - hybridly/laravel[v0.1.0, ..., v0.6.0] require illuminate/contracts ^9.0|^10.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.22] but these were not loaded, likely because it conflicts with another require.
          - hybridly/laravel v0.6.1 requires illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.22] but these were not loaded, likely because it conflicts with another require.
          - hybridly/laravel[v0.7.0, ..., v0.7.14] require laravel/prompts ^0.1 -> found laravel/prompts[v0.1.0, ..., v0.1.25] but the package is fixed to v0.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument
for the update command.
          - Root composer.json requires hybridly/laravel * -> satisfiable by hybridly/laravel[v0.1.0, ..., v0.7.14].

      Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
      You can also try re-running composer require with an explicit version constraint, e.g. "composer require hybridly/laravel:*" to figure out if any version is installable, or "composer require hybridly/laravel:^2.1" if you know which you need.

      Installation failed, reverting ./composer.json and ./composer.lock to their original content.
  ✓  Executed action: add php dev dependencies (php)
  ✓  Executed action: publish typescript transformer config
  ✓  Executed action: update typescript transformer config
  ✓  Executed action: update welcome route
  ✓  Executed action: apply strict mode
  ✓  Executed action: setup ide helper (2 actions)

 Presets  1 applied | 1 failed (2)
 Actions  21 executed | 1 failed (22)
Duration  58.51s


  ERR_PRESET_FAILED  Some of the actions of the preset failed.
```

I tried with: yarn, npm and bun, without success!

I tried to install it manually, but without success:
![image](https://github.com/user-attachments/assets/a626293d-afdd-483e-8c72-0016524bce7b)

php: 8.2
fresh laravel 11 via:
composer create-project laravel/laravel hybridly-app

### Reproduction

none

### Steps to reproduce

1 - Create fresh laravel app
2 - Attempt to install package

### System information

```bash
MacOs
Php 8.2
Bun/Yarn/Npm
```

### Used package manager

yarn

### Logs

None

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cgslivre** [comment]
Workaround:
1 - Create fresh laravel app
```sh
composer create-project laravel/laravel path/to/app
```
2 - Downgrade laravel/prompts:
```sh
cd path/to/app
composer require laravel/prompts:^0.1 --dev
```
![image](https://github.com/user-attachments/assets/7a78c32e-9144-48ef-a892-2e1f42116c5d)


3 - apply preset
```sh
# bun, nmp or yarn
bunx @preset/cli apply hybridly/preset
```
![image](https://github.com/user-attachments/assets/3d5c5837-04b4-444f-ad81-bb5ccfdc197b)

Possible solution:
Change laravel/prompts required version range
![image](https://github.com/user-attachments/assets/839648cf-8025-4852-a33e-a031633e0410)

**Comment by innocenzi** [comment]
Hey, thanks for the report! I updated the preset, can you try again?

**Comment by cgslivre** [comment]
Perfect! Thanks for the super fast action!

![image](https://github.com/user-attachments/assets/9fadfdf8-fc49-4f26-923a-15446f0f0fe4)
