### ISSUE TITLE
The registerHook function does not get unregistered automatically on unmount

### ISSUE THREAD

**Issue by HassanZahirnia** [hybridly/hybridly#27]
### Describe the bug

When you have 2 different persistent layouts, and you add a `registerHook` to each one, when you navigate between them the `registerHook` for both will run. It appears the `registerHook` does not gets unregistered on component `unMounted` cycle.

### Reproduction

-

### System information

```bash
"hybridly": "0.0.1-alpha.16"
```

### Used package manager

pnpm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/hybridly/hybridly/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
To fix this, we would have to create a `registerHook` function in the `vue` package with the exact same signature. This function would call the original `registerHook` from `core`, and call its `unregister` function in an `onUnmounted` call **only if** we are in a component's lifecycle (eg. `getCurrentInstance` returns something).
