### ISSUE TITLE
Form Errors Reactivity & Nested Fields Errors

### ISSUE THREAD

**Issue by nikuscs** [hybridly/hybridly#71]
### Describe the bug

There is def. something weird with the errors and im not sure yet why, but ill leave this issue to follow up

- The first i noticed while investigating some time ago, is that errors behave in a weird way in hybridly ( and a bit different from inertia ), when the backend sends the same error twice for a specific field, the errors variable is not triggered again ( and makes sense since the message is the same, and so the value never changes, so it will not trigger the watch effect. I believe this is related to original issue, reason why i wanted to mention.

- Seems like when using nested fields in forms, if we submit and the field has an error, the error is correctly set and all good here, but if you attempt to fill the said field ( so it does not contain errors ), the form.errors for that specific field seems like its never removed, while the server sends back a response without the given error shared. Its expected that also nested fields are also cleared when they are not present.

- Please do note that is also breaks the watch effect, so if you have a v-if for the given error, it will always be shown, because the variable is never removed.
 
 The only way to proper workaround this is to use the before hook to clear the given fields, but i believe this should be looked properly to have a smooth expirience.
 
 
 To note also that nested fields errors must be accessed with `form.errors['foo.nested']` instead of dot notation, ( not 100% sure but i believe it would be a nice DX to provide nested navigation for those as well.
 

### Reproduction

https://github.com/nikuscs/hybridly-demo-validation-errors

### Steps to reproduce

- Visit the https://blue-bird.test/login
- First submit without the nested field so it the error is flashed
- Then fill the contents of nested field and send again
- Errors for the given field will not be sent back by the server, but still persisted in errors
- Watch console for proper errors.

### System information

```bash
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 201.41 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/Library/Caches/fnm_multishells/68334_1681237407108/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - ~/Library/Caches/fnm_multishells/68334_1681237407108/bin/npm
  Browsers:
    Brave Browser: 112.1.50.114
    Chrome: 111.0.5563.146
    Firefox: 110.0
    Safari: 16.4
```

### Used package manager

pnpm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nhedger** [comment]
FYI, I have started looking into this.

**Comment by nhedger** [comment]
I could use some help linking my local copy of hybridly into the Laravel skeleton.

Using the following in my package.json does not seem to be enough

```json
"hybridly": "file:../hybridly/packages/hybridly/dist",
```

Starting Vite in dev mode results in the following error.

```
> @ dev /Users/nicolas/Contributing/issue-71
> vite

failed to load config from /Users/nicolas/Contributing/issue-71/vite.config.ts
error when starting dev server:
Error: Cannot find module 'hybridly/vite'
Require stack:
- /Users/nicolas/Contributing/issue-71/vite.config.ts
- /Users/nicolas/Contributing/issue-71/node_modules/.pnpm/vite@4.3.3_@types+node@18.16.1/node_modules/vite/dist/node/chunks/dep-a178814b.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/nicolas/Contributing/issue-71/vite.config.ts:37:28)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at _require.extensions.<computed> [as .js] (file:///Users/nicolas/Contributing/issue-71/node_modules/.pnpm/vite@4.3.3_@types+node@18.16.1/node_modules/vite/dist/node/chunks/dep-a178814b.js:64432:24)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
 ELIFECYCLE  Command failed with exit code 1.
```

What is your setup when developing Hybridly @innocenzi ?

**Comment by innocenzi** [comment]
@nhedger I simply `pnpm i /path/to/hybridly` (note this is the path to the package root, not to its dist), pnpm does the symlink automatically. Hybridly has to be built too, and you have to build it after each change (eg. `nr --filter vue build`)

**Comment by nhedger** [comment]
Weird, my setup is mostly the same. I'll try again later today. Thanks

**Comment by innocenzi** [comment]
FWIW I use an absolute path, not a relative one, and it's the path to `/hybridly/packages/hybridly`, not `/hybridly/packages/hybridly/dist`

**Comment by nhedger** [comment]
This did the trick.

```
pnpm add ../hybridly/packages/hybridly
```

I was actually using `file:../hybridly/packages/hybridly` where I should have used `link:../hybridly/packages/hybridly`

Also, the path I was using was incorrect.

**Comment by nhedger** [comment]
The offending method seems to be `clearErrors`

https://github.com/hybridly/hybridly/commit/7daa3f29bcf37cee4fed6db8246d0eff3db66f2d

Using this seems to fix the problem:

```ts
function clearErrors(...keys: (keyof T)[]) {
    errors.value = {}
}
```

I see this was the previous implementation too. As far as I can tell, clearErrors for clearing individual fields is actually never used, so maybe we could just revert for now.

**Comment by innocenzi** [comment]
The issue would actually be the implementation of `clearError` then? Does it have something to do with `delete`?

**Comment by nhedger** [comment]
Could be. Logging the before and after yields the same. Could be that the value is not updated.

AFAIK delete on a reactive value should work in vue 3, but I could be mistaken.

**Comment by nhedger** [comment]
Ok, so when no custom keys are specified, we take the properties of the `fields`.

https://github.com/hybridly/hybridly/blob/8f3294eee92745c4cd5f748e85ba51cdc6426dfc/packages/vue/src/composables/form.ts#L181-L183

When using `useForm`, those fields would have been declared something like the following:

```ts
const form = useForm({
    url: '/test',
    method: 'POST',
    fields: {
        name: '',
        phone: {
            work: ''
        }
    }
})
```

The problem seems to be that when supplying a nested structure as the input (which we are doing here), the error key returned by the backend is actually a dot-notated path.

```json
{ 
  "phone.work": "The phone.work field is required.", 
  "name": "The name field is required." 
}
```

So Hybridly's trying to clear a non-existing `phone` key on the errors object, where really it should be trying to delete the `phone.work` key.

### Possible solution

We would reconstruct the path to the key from the dot-notated path, it seems fairly simple and changing the way errors are returned by the backend would imply breaking changes.

**Comment by nikuscs** [comment]
in my opinion nested errors should be unpacked and set as an array of errros, this is ( for me ) what would make more sense.

**Comment by nhedger** [comment]
How would that look like @nikuscs ?

**Comment by nikuscs** [comment]
> How would that look like @nikuscs ?

This can either be server sided when hybridly shares errors with something like Arr::undot() or either on the frontend, actually for my inertia apps i used to do this, then you would expect the same object structure as you define it ( nested )

**Comment by nhedger** [comment]
This would be considered a breaking change IMHO. I think it would be better to focus on solving the issue first, and then opening another to discuss changing the current implementation. What do you think ?

**Comment by innocenzi** [comment]
Should be fixed by https://github.com/hybridly/hybridly/pull/74 thanks to @nhedger, will be included in next release
