### ISSUE TITLE
Root Blade view is not resolved relative to the `architecture.root` path

### ISSUE THREAD

**Issue by nhedger** [hybridly/hybridly#80]
### Describe the bug

Hybridly cannot locate the root Blade view when the `architecture.root` option is set to an alternative path.

#### Current behaviour

Hybridly always attempts to locate the root Blade view at `resources/application/root.blade.php`.

#### Expected behaviour

Hybridly should attempt to locate the root Blade view at `{architecture.root}/application/root.blade.php`

### Reproduction

https://github.com/nhedger/hybridly-root-view-issue

### Steps to reproduce

1. Setup a new Laravel application: `laravel new hybridly-root-view-issue`
2. Apply the preset to the new installation: `pnpm dlx @preset/cli apply hybridly/preset`
3. Publish Hybridly's configuration file: `php artisan vendor:publish --tag hybridly-config`
4. Change the `architecture.root` option from `resources/` to `frontend/`
5. Move the contents of the `resources/` folder to the `frontend/` folder
6. Run `php artisan serve` and attempt to load the page.
7. Assert that an `View [root] not found.` error is shown.

### System information

```bash
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.67 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/22511_1687367505328/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/22511_1687367505328/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/22511_1687367505328/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.51
    Safari: 16.4
  npmPackages:
    hybridly: ^0.4.0 => 0.4.0
```

### Used package manager

pnpm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by innocenzi** [comment]
Should be fixed in https://github.com/hybridly/hybridly/commit/b07f13c7786a47da26def40fd56ec139d5864933, can you try using https://github.com/hybridly/hybridly/tree/0.x locally and tell me if that works for you?

**Comment by nhedger** [comment]
Yep, that fixed the issue. Thanks for looking into it.
