### ISSUE TITLE
Hybridly unregisters Laravel's default view folder

### ISSUE THREAD

**Issue by nhedger** [hybridly/hybridly#88]
### Describe the bug

I believe that Hybridly may be unregistering Laravel's default `resources/views` folder.

I would not expect Hybridly to do so.

### Reproduction

n/a

### Steps to reproduce

In a fresh project **without** hybridly installed:

```shell
~/Code/without-hybridly php artisan tinker
Psy Shell v0.11.20 (PHP 8.2.7 — cli) by Justin Hileman
> app(Illuminate\View\Factory::class)->getFinder()->getPaths();
= [
    "/Users/nicolas/Code/without-hybridly/resources/views",
  ]
```

In a fresh project with hybridly installed (using the preset with defaults):

```shell
~/Code/with-hybridly php artisan tinker
Psy Shell v0.11.20 (PHP 8.2.7 — cli) by Justin Hileman
> app(Illuminate\View\Factory::class)->getFinder()->getPaths();
= [
    "/Users/nicolas/Code/with-hybridly/resources",
    "/Users/nicolas/Code/with-hybridly/frontend/application",
  ]
```

As you can see, the `resources/views` folder is no longer available.

### System information

```bash
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 902.06 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/30173_1690994804380/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/30173_1690994804380/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/30173_1690994804380/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.79
    Safari: 16.5.2
  npmPackages:
    hybridly: ^0.4.2 => 0.4.2
```

### Used package manager

pnpm

### Validations

- [X] Read the [docs](https://hybridly.dev).
- [X] Check that there isn't [already an issue](https://github.com/hybridly/hybridly/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Hybridly issue and not an issue related to something else (Vite, Vue...). For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A, join our [Discord server](https://discord.gg/uZ8eC7kRFV).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by godismyjudge95** [comment]
Yeah it does that as a part of the preset config.  It looks like it was done to fix view caching:  https://github.com/hybridly/preset/blob/3b0cfdea4d55985568558c57e495fd5c8605652c/preset.ts#L214-L221

**Comment by nhedger** [comment]
Oh, good catch. It didn't occur to me that it was the preset. Thanks!

Not sure what bug this is trying to solve, though.

---

I just reverted this specific change and ran `php artisan view:cache` with success.

**Comment by godismyjudge95** [comment]
If you look at what `view:cache` is caching though, it won't cache anything not in the `view.paths` config value:
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Console/ViewCacheCommand.php

That means the default Hybridly layout file in `resources/application/root.blade.php` would not be compiled and cached.

I suppose you could get around this by adding an additional path to the paths array specifically for `resources/application` but idk what additional implications that would have.

**Comment by nhedger** [comment]
Looks like Hybridly's already doing that: https://github.com/hybridly/hybridly/blob/8fa08cd444094b43af3db2faf464df97966d2c64/packages/laravel/src/HybridlyServiceProvider.php#L45-L47C12.

At least it does since two months. It could be that the preset is just outdated.

**Comment by godismyjudge95** [comment]
Huh, yeah it might be that fix was from before Hybridly hooked in like that.
